name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  base-cuda116-cudnn8-devel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: 11.6.0-cudnn8-devel-ubuntu20.04
            tag: base-cuda11.6-cudnn8-devel
          - image: 11.6.0-cudnn8-runtime-ubuntu20.04
            tag: base-cuda11.6-cudnn8-runtime
          - image: 11.6.0-devel-ubuntu20.04
            tag: base-cuda11.6-devel
          - image: 11.6.0-runtime-ubuntu20.04
            tag: base-cuda11.6-runtime
          - image: 11.6.0-base
            tag: base-cuda11.6
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push CUDA11.6-CuDNN8-devel
        env:
          IMAGE: ${{ matrix.image }}
          TAG: ${{ matrix.tag }}
        working-directory: ./basic
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --build-arg BASE_IMAGE=nvidia/cuda:$IMAGE \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/basic-ml:$TAG \
            --file Dockerfile \
            .